// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3vcvRkeE_YA9gl1Nv5rDGtF9_uaCUgM',
    appId: '1:657137959635:web:af80d7d4f48b3b579fca26',
    messagingSenderId: '657137959635',
    projectId: 'elmazon1',
    authDomain: 'elmazon1.firebaseapp.com',
    storageBucket: 'elmazon1.appspot.com',
    measurementId: 'G-XX99H9N3WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1g4ecX8SKbJQCe2t67nRJu1lndPEKxoo',
    appId: '1:657137959635:android:6ef7e93ecf92b9439fca26',
    messagingSenderId: '657137959635',
    projectId: 'elmazon1',
    storageBucket: 'elmazon1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgew1nCR6fEv2r8OPS7uZsUT0TbRdw98',
    appId: '1:657137959635:ios:7022481ebee014289fca26',
    messagingSenderId: '657137959635',
    projectId: 'elmazon1',
    storageBucket: 'elmazon1.appspot.com',
    iosBundleId: 'com.topbusiness.newMazoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgew1nCR6fEv2r8OPS7uZsUT0TbRdw98',
    appId: '1:657137959635:ios:7022481ebee014289fca26',
    messagingSenderId: '657137959635',
    projectId: 'elmazon1',
    storageBucket: 'elmazon1.appspot.com',
    iosBundleId: 'com.topbusiness.newMazoon',
  );
}
